lawcater/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path,include
from django.conf.urls.static import static
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
     path('', include('lawcaterapp.urls')),

    # path('lawcater/', include('lawcater.urls')),
    path('tinymce/', include('tinymce.urls')),

]+ static(settings.MEDIA_URL, document_root =settings.MEDIA_ROOT)

lawcaterapp/urls.py
from . import views
from django.urls import path
from .views import *
from django.urls import path,include
from django.views.generic import TemplateView


urlpatterns = [
    path('', home, name = 'home'),
    #  path('story/', Story, name = 'story'),

# path("", homepage.as_view(), name='home'),


     path('post/<slug>/', detail, name = 'detail'),
      # path('blog/<id>', Blog, name = 'blog'),

    # path('post/<slug>/', post, name = 'post'),

      # path("team/", team, name="team"),
      path("team/", team.as_view(), name='team'),

     path("contact/", contact, name="contact"),
      # path("contact/", contact.as_view(), name='contact'),


    #  path("sendmail/", sendmail, name="sendmail"),

    #  path('/sendmail/',TemplateView.as_view(template_name='home.html')),

      path('<slug:slug>/', postByCategory, name = 'category'),


]

lawcaterapp/models.py
from django.db import models
from django.contrib.auth import get_user_model
from  embed_video.fields  import  EmbedVideoField

from tinymce.models import HTMLField
from datetime import datetime, date
from django.urls import  reverse
from mimetypes import guess_type


class Category(models.Model):
    cat_id =models.AutoField(primary_key=True)
    title = models.CharField(max_length=20)
    slug = models.SlugField(max_length=1000)


    def __str__(self):
        return self.title


class Post(models.Model):
    post_id =models.AutoField(primary_key=True)
    title = models.CharField(max_length=100)
    slug = models.SlugField(max_length=200)
    # timestamp = models.DateTimeField(auto_now_add=True)
    timestamp = models.DateTimeField(auto_now_add=False,auto_now=False,blank=True,null=True)
    timestamps = models.DateTimeField(auto_now_add=True,auto_now=False,blank=True,null=True)
    video = EmbedVideoField(null=True, blank=True)

    content = HTMLField()
    author = models.CharField(max_length=50,null=True, blank=True)
    categories = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='post/',default='default.jpg')
    publish=models.BooleanField()
    read=models.IntegerField(default=0)




    class Meta:
        ordering=['-post_id']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
       return reverse('lawcaterapp:post_detail',args=[self.id,])




class Comment(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE,related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)

    class Meta:
        ordering = ['created_on']

    def __str__(self):
        return 'Comment {} by {}'.format(self.body, self.name)

lawcaterapp/forms.py
from .models import Comment
from django import forms



class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

class ContactForm(forms.Form):
	first_name = forms.CharField(max_length = 50)
	last_name = forms.CharField(max_length = 50)
	email_address = forms.EmailField(max_length = 150)
	message = forms.CharField(widget = forms.Textarea, max_length = 2000)

lawcaterapp/views.py
from .models import Post, Category
from .forms import CommentForm, ContactForm
from django.shortcuts import render, get_object_or_404
from django.core.mail import send_mail, BadHeaderError
from django.shortcuts import render, redirect
from django.core.mail import send_mail
from lawcaterapp.forms import ContactForm
from django.core.paginator import Paginator , EmptyPage, PageNotAnInteger
from django.http import HttpResponse
from django.views.generic import TemplateView

# Create your views here.

# def homepage(request):
#     cats = Category.objects.all()
#     posts = Post.objects.filter()[0:6]

#     context= {

#         'posts':posts,
#         'cats':cats,
#     }
#     return render(request, 'homepage.html',context)

# class homepage(TemplateView):
#     template_name = "index.html"


#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context['allcategories'] = Category.objects.all()
#         return context

def home(request):
    categories = Category.objects.all()[:3]
    page =Paginator(categories, 3)
    page_list = request.GET.get('page')
    page = page.get_page(page_list)

    context = {
        "allcategories": categories,
    }
    return render(request,'index.html', context)


class team(TemplateView):
    template_name = "team.html"


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['allcategories'] = Category.objects.all()
        return context

# for post detail
def detail(request, slug):
    cats = Category.objects.all()

    # post = get_object_or_404(Post, slug=slug)
    post = Post.objects.filter(slug=slug).first()

    comments = post.comments.filter(active=True)
    # post= Post.objects.get(slug=slug)
    new_comment = None

    # Comment posted
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()
    else:
        comment_form = CommentForm()
    return render(request, 'blog-detail.html', {'post': post,
                                           'comments': comments,
                                           'new_comment': new_comment,
                                           'comment_form': comment_form,
                                           'allcategories':cats})

    # context = {
    #     'post': post,
    # }
    # return render(request, 'blog-detail.html', context)

# def Blog (request ):
#     cats = Category.objects.get(cat_id = id)
#     posts=Post.objects.filter(category=cats)
#     posts = Post.objects.filter(categories__in=[category])
#     context = {
#         'cat':cats,
#         'posts': posts,
#     }
#     return render(request, 'blog.html')

#categorywise item
def postByCategory(request,slug):
    cats = Category.objects.all()
    cat=Category.objects.get(slug=slug)
    posts=Post.objects.filter(categories_id=cat)

    page =Paginator(posts, 6)
    page_list = request.GET.get('page')
    page = page.get_page(page_list)

    # try:
    #     posts_page=all_post.page(page)
    # except PageNotAnInteger:
    #     posts_page = all_post.page(1)
    # except EmptyPage:
    #     posts_page= all_post.page(all_post.num_pages)


    return render(request, "blog.html",{'page':page,'cat':cat, 'posts':posts,'allcategories':cats})



# def contact(request):
#     return render(request, 'contact.html')


# def sendmail(request):
#     form = ContactForm(request.POST)
#     if form.is_valid():
#         subject = form.cleaned_data['subject']
#         message = form.cleaned_data['message']
#         sender = form.cleaned_data['sender']
#         cc = form.cleaned_data['cc']
#         recipients = ['urgenlama33@gmail.com']
#         recipients.append(sender)
#         send_mail(subject, message, sender, recipients)
#         return render(request,'home.html')

#     else:
#         form = ContactForm()
#         return render(request,'contact.html',{'form':form})

# def contact(request):
#     if request.method == 'POST':
#         form = ContactForm(request.POST)
#         subject = "Website Inquiry"
#         body = {
# 			'first_name': form.cleaned_data['first_name'],
# 			'last_name': form.cleaned_data['last_name'],
# 			'email': form.cleaned_data['email_address'],
# 			'message':form.cleaned_data['message'],
# 			}
#         message = "\n".join(body.values())
#         send_mail(
#             subject,
#             message,
#             ['lawcaters@gmail.com'],
#             fail_silently=False,
#         )

#         return render(request,'contact.html')
#     else:
#         return render(request,'contact.html')
# def contact(request):
#     if request.method == 'POST':
#         name = request.POST.get('name')
#         subject = request.POST.get( 'subject')
#         message = request.POST.get('message')
#         email = request.POST.get('email')
#         data={
#             'name':name,
#             'email':email,
#             'subject':subject,
#             'message':message
#                 }

#         send_mail(data['subject'], message,'',['lawcaters@gmail.com'],
#         fail_silently=False)
#         return HttpResponse('thank you')
#     return render(request,'contact.html',{})


# def contact(request):

#     allcategories = Category.objects.all()
#     if request.method == 'POST':
#         name = request.POST.get('name')
#         email = request.POST.get('email')
#         phone = request.POST.get('phone')
#         message = request.POST.get('message')
#         form_data = {
#             'name':name,
#             'email':email,
#             'phone':phone,
#             'message':message,
#         }
#         message = '''
#         From:\n\t\t{}\n
#         Message:\n\t\t{}\n
#         Email:\n\t\t{}\n
#         Phone:\n\t\t{}\n
#         '''.format(form_data['name'], form_data['message'], form_data['email'],form_data['phone'])
#         send_mail('You got a mail!', message, '', ['lawcaters@gmail.com']) # TODO: enter your email address

#     return render(request, 'contact.html', {})


def contact(request):

    allcategories = Category.objects.all()

    if request.method == 'POST':
        name = request.POST.get('name')
        email = request.POST.get('email')
        phone = request.POST.get('phone')
        message = request.POST.get('message')
        form_data = {
            'name':name,
            'email':email,
            'phone':phone,
            'message':message,
        }
        message = '''
        From:\n\t\t{}\n
        Message:\n\t\t{}\n
        Email:\n\t\t{}\n
        Phone:\n\t\t{}\n
        '''.format(form_data['name'], form_data['message'], form_data['email'],form_data['phone'])
        send_mail('You got a mail!', message, '', ['lawcaters@gmail.com']) # TODO: enter your email address

    return render(request, 'contact.html',  {

                                           'allcategories': allcategories})

lawcaterapp/templates/blog-detail.html
{% extends 'common.html' %} {% block title %} Story {% endblock %}
{% block body %}
 {% load static %}
 <style>
   .comment-section{
    margin-top:20px;
    background-color:#e9ebee;
}

.be-comment-block {
    margin-bottom: 50px !important;
    border: 1px solid #edeff2;
    border-radius: 2px;
    padding: 50px 10px;
    border:1px solid #ffffff;
}

.comments-title {
    font-size: 16px;
    color: #262626;
    margin-bottom: 15px;
    font-family: 'Conv_helveticaneuecyr-bold';
}

.be-img-comment {
    width: 60px;
    height: 60px;
    float: left;
    margin-bottom: 15px;
}

.be-ava-comment {
    width: 60px;
    height: 60px;
    border-radius: 50%;
}

.be-comment-content {
    margin-left: 3rem;
}

.be-comment-content span {
    display: inline-block;
    width: 49%;
    margin-bottom: 15px;
}

.be-comment-name {
    font-size: 13px;
    font-family: 'Conv_helveticaneuecyr-bold';
}

.be-comment-content a {
    color: #383b43;
}

.be-comment-content span {
    display: inline-block;
    width: 49%;
    margin-bottom: 15px;
}

.be-comment-time {
    text-align: right;
}

.be-comment-time {
    font-size: 11px;
    color: #b4b7c1;
}

.be-comment-text {
    font-size: 13px;
    line-height: 18px;
    color: #7a8192;
    display: block;
    background: #f6f6f7;
    border: 1px solid #edeff2;
    padding: 15px 20px 20px 20px;
}

.form-group.fl_icon .icon {
    position: absolute;
    top: 1px;
    left: 16px;
    width: 48px;
    height: 48px;
    background: #f6f6f7;
    color: #b5b8c2;
    text-align: center;
    line-height: 50px;
    -webkit-border-top-left-radius: 2px;
    -webkit-border-bottom-left-radius: 2px;
    -moz-border-radius-topleft: 2px;
    -moz-border-radius-bottomleft: 2px;
    border-top-left-radius: 2px;
    border-bottom-left-radius: 2px;
}

.form-group .form-input {
    font-size: 13px;
    line-height: 50px;
    font-weight: 400;
    color: #b4b7c1;
    width: 100%;
    height: 50px;
    padding-left: 20px;
    padding-right: 20px;
    border: 1px solid #edeff2;
    border-radius: 3px;
}

.form-group.fl_icon .form-input {
    padding-left: 70px;
}

.form-group textarea.form-input {
    height: 150px;
}

.comment {
    width: 72vw;
    /* margin: 1rem auto; */
    margin: 2rem auto;
}

/* .wrapper {
  position: absolute;
  top: 30%;
  left: 8%;
  transform: translate(-50%, -50%);



}
.wrapper {
    position: absolute;
    top: 29.5%;
    left: 40%;
    transform: translate(-49%, -55%);
    margin: 0.2rem auto;
    position: fixed;

}
.wrapper li{
    display: flex;
}
.wrapper ul div {
    width: 25px;
    height: 25px;

    margin: 20px 10px;
    position: relative;
  cursor: pointer;
  border-radius: 50%;
  box-shadow: 0 0 10px rgba(0,0,0,0.3);

} */
/* .icon-media {
    position: absolute;
    top: 30%;
    left: 35%;
    transform: translate(-50%, -50%);
    font-size: 28px;

} */
ul {
  list-style: none;
}
/* .wrapper ul div {
  width: 40px;
  height: 40px;


  margin: 10px 0;


} */
.icon-media {
    position: absolute;
    top: 30%;
    left: 30%;
    transform: translate(-50%, -50%);
    font-size: 28px;


}



 </style>

 <section class=" parent ">

    <div class="banner_inner child">

            <div class="image detail-blog">
                <!-- <img  class="img-fluid" src="img/banner/home-banner.jpg" alt="roller coaster"> -->

                <img  class="img-fluid" src="/media/{{post.image}}" alt="roller coaster">


            </div>



    </div>









<div class="child stack-top">



    <h1 class="text-center">{{post.title}} </h1>
    <div class="wrapper">
        <ul>
    <li>
    {% load social_share %}

    {% post_to_facebook object_or_url '<i class="fa fa-facebook icon-media" aria-hidden="true"></i>' %}


    {% post_to_twitter "Share: {{object.title}}" object_or_url '<i class="fa fa-twitter icon-media" aria-hidden="true"></i>' %}
    {% post_to_whatsapp object_or_url '<i class="fa fa-whatsapp icon-media" aria-hidden="true"></i>'%}
    {% post_to_telegram "Share: {{object.title}}" object_or_url '<i class="fab fa-telegram icon-media" aria-hidden="true"></i>'  %}

    </li>
    </ul>
    </div>

    {% if post.video %}


        <div class="embed-responsive embed-responsive-16by9 youtube-video">


        <iframe class="embed-responsive-item" src="{{post.video}}" allowfullscreen>{{post.video}}</iframe> -->

    </div>
    {% else %}
        <img class= "image-blog" src="/media/{{post.image}}"/>
        <!-- or <img src="{% static 'Path/To?You/static/image.png' %}"/> if You not upload image everytime-->
    {% endif %}







    <!-- <img class="image-fit" src="/media/{{post.image}}" alt="girl"> -->

    <!-- <div class="embed-responsive embed-responsive-16by9 youtube-video"> -->
        <!-- {{post.video}} -->
<!--
        <iframe class="embed-responsive-item" src="{{post.video}}" allowfullscreen>{{post.video}}</iframe> -->

    <!-- </div> -->


    <!-- <img src="img/blog/image2.png"  alt="carrying bag"> -->
    <div class="content-main">
    <p class="qodef-m-text"> {{post.content|safe}} </p>

        <p class="qodef-m-text"></p>
        </p>
            <!-- <div class="single-img">
            <img  class= "image-fit" src="img/blog/image2.png"  alt="carrying bag">
            </div> -->

          <!-- <h4 class="font-weight-bold">
            -{{post.author}}
          </h4> -->

    </div>
</div>


</section>



<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
<div class="container comment-section">
<div class="be-comment-block">
	<h1 class="comments-title">Comments </h1>
    {% for comment in comments %}

	<div class="be-comment">
		<!-- <div class="be-img-comment">
			<a href="blog-detail-2.html">
				<img src="https://bootdey.com/img/Content/avatar/avatar1.png" alt="" class="be-ava-comment">
			</a>
		</div> -->
		<div class="be-comment-content">
  {% load crispy_forms_tags %}
				<span class="be-comment-name">
					<a href="blog-detail-2.html"> {{ comment.name }}</a>
					</span>
				<span class="be-comment-time">
					<i class="fa fa-clock-o"></i>
                    {{ comment.created_on }}
				</span>

			<p class="be-comment-text">
                {{ comment.body  }}
			</p>
		</div>
	</div>
    {% endfor %}


    <div class="">
        {% if new_comment %}
        <div class="alert alert-success" role="alert">
          Your comment is awaiting moderation
        </div>
        {% else %}
        <h1 class="comments-title">Leave a comment</h1>
        {% load crispy_forms_tags %}
        {% if user.is_authenticated %}
        <div class="comment">
        <form method="POST">
          {% csrf_token %}
          <div class="form-block">
            {{ comment_form | crispy }}
            <button class="btn btn-info" type="submit">Add comment </button>
          </div>
        </form>
    </div>

        {% endif %}

    <!-- <form class="form-block"> -->

    </div>

		<div class="row">


 <!-- <div class="col-xs-12 col-sm-6">
				<div class="form-group fl_icon">
					<div class="icon"><i class="fa fa-user"></i></div>
					<input class="form-input" type="text" placeholder="Your name">
				</div>
			</div>
			<div class="col-xs-12 col-sm-6 fl_icon">
				<div class="form-group fl_icon">
					<div class="icon"><i class="fa fa-envelope-o"></i></div>
					<input class="form-input" type="text" placeholder="Your email">
				</div>
			</div>
			<div class="col-12">
				<div class="form-group">
					<textarea class="form-input" required="" placeholder="Your text"></textarea>
				</div>
			</div>
			<a class="btn btn-primary pull-right">submit</a>
		</div> -->

    {% endif %}
</div>
</div>
</div>


 {% endblock %}

lawcaterapp/templates/index.html
{% extends 'common.html' %} {% block title %} Lawcater {% endblock %}
{% block body %}
 {% load static %}

 <section>
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img class="d-block w-100" src="{% static 'img/end.png' %}" alt="First slide">
          </div>
          <div class="carousel-item">
            <img class="d-block w-100" src="{% static 'img/anxiety.png' %}" alt="Second slide">
          </div>
          <div class="carousel-item">
            <img class="d-block w-100" src="{% static 'img/group.jpg' %}" alt="Third slide">
          </div>
        </div>
        <div class="carousel-caption d-none d-md-block">
            <!-- <h5>.jhh..</h5>
            <p>..hfhfh.</p> -->
          </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
</section>



<!-- Blog -->
<section class="section_gap blog_area">
    {%  for cat in allcategories %}
	<div class="container">
		<div class="row justify-content-center">
			<div class="col-lg-7">
				<div class="main_title">
					<h2> Our  {{ cat.title }}</h2>
					<!-- <p>Lorem ipsur adipisicing elit, sed eiusmod tempor incididunt labore dolore magna
						aliqua enim minim veniam quis nostrud.</p> -->
				</div>
			</div>
		</div>

		<div class="row justify-content-center">
			<!-- single-blog -->



            {% for i in cat.post_set.all|slice:":6" %}

			<div class="col-lg-4 col-md-4 col-sm-6">
				<div class="single-blog">
					<div class="blog-thumb">
						<img class="img-fluid img-home" src="/media/{{i.image}}" alt="">
					</div>
					<div class="blog-details">
						<div class="blog-meta">
							<span>{{i.timestamp|date:"F d, Y"}} </span>
						</div>
						<h5><a href="/post/{{i.slug}}">{{i.title}} <br>
								</a></h5>
						<!-- <p>{{i.content}}</p> -->
					</div>
				</div>
			</div>

            {% endfor %}
            <!-- <a href="-blog/" class="btn btn-info ">Read More</a> -->

			<!-- single-blog -->
			<!-- <div class="col-lg-4 col-md-4 col-sm-6">
				<div class="single-blog">
					<div class="blog-thumb">
						<img class="img-fluid" src="{% static 'img/blog/h-blog2.jpg' %}" alt="">
					</div>
					<div class="blog-details">
						<div class="blog-meta">
							<span>25 june, 2018 | By Mark Wiens</span>
						</div>
						<h5><a href="#">Addiction When Gambling <br>
								Becomes A Problem</a></h5>
						<p>Computers have become ubiquitous in almost every facet of our lives. At work, desk jockeys spend hours in
							front of their desktops.</p>
					</div>
				</div>
			</div> -->
			<!-- single-blog -->
			<!-- <div class="col-lg-4 col-md-4 col-sm-6">
				<div class="single-blog">
					<div class="blog-thumb">
						<img class="img-fluid" src="{% static 'img/blog/h-blog3.jpg' %}" alt="">
					</div>
					<div class="blog-details">
						<div class="blog-meta">
							<span>25 june, 2018 | By Mark Wiens</span>
						</div>
						<h5><a href="#">Addiction When Gambling <br>
								Becomes A Problem</a></h5>
						<p>Computers have become ubiquitous in almost every facet of our lives. At work, desk jockeys spend hours in
							front of their desktops.</p>
					</div>
				</div>
			</div> -->
            <br>
            <div class="text-center">
                <a href="/{{cat.slug}}" type="button" class="btn button  view-more">View All</a>
              </div>
		</div>


	</div>
    {% endfor %}
</section>


<section class="section_gap teams team-area">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-7">
                <div class="main_title">
                    <h2>Meet Our Experienced Team</h2>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed eiusmod tempor incididunt labore dolore magna
                        aliqua enim minim veniam quis nostrud.</p>
                </div>
            </div>
        </div>
        <div class="row justify-content-center">
            <!-- single-team-member -->
            <div class="col-lg-4 col-md-4 col-sm-6">
                <div class="single_member">
                    <div class="author">
                        <img class="img-fluid" src="{% static 'img/team/smriti.jpg' %}" alt="girl">
                    </div>
                    <div class="author_decs">
                        <h5>Smriti Paudel</h5>
                        <p class="profession">Admin/Director</p>
                    </div>
                </div>
            </div>
            <!-- single-team-member -->
            <div class="col-lg-4 col-md-4 col-sm-6">
                <div class="single_member">
                    <div class="author">
                        <img class="img-fluid" src="{% static 'img/team/shrijala.jpg' %}" alt="girl">
                    </div>
                    <div class="author_decs">
                        <h5>Shrijala Pandey</h5>
                        <p class="profession">Content Creator</p>
                    </div>
                </div>
            </div>
            <!-- single-team-member -->
            <div class="col-lg-4 col-md-4 col-sm-6">
                <div class="single_member">
                    <div class="author">
                        <img class="img-fluid" src="{% static 'img/team/sejal.jpg' %}" alt="girl">
                    </div>
                    <div class="author_decs">
                        <h5>Sejal Acharya</h5>
                        <p class="profession">Researcher</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-4 col-sm-6">
                <div class="single_member">
                    <div class="author">
                        <img class="img-fluid" src="{% static 'img/team/binit.jpg' %}" alt="boy">
                    </div>
                    <div class="author_decs">
                        <h5>Binit BT Magar</h5>
                        <p class="profession">Cameraperson</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-4 col-sm-6">
                <div class="single_member">
                    <div class="author">
                        <img class="img-fluid" src="{% static 'img/team/pranab.jpg' %}" alt="boy">
                    </div>
                    <div class="author_decs">
                        <h5>Pranab Pokharel</h5>
                        <p class="profession">IT Architect</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<!--================ Start Blog Area =================-->
<!-- <section class="section_gap blog_area">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-7">
                <div class="main_title">
                    <h2>Latest From Our Blog Posts</h2>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed eiusmod tempor incididunt labore dolore magna
                        aliqua enim minim veniam quis nostrud.</p>
                </div>
            </div>
        </div>
        <div class="row justify-content-center">

            <div class="col-lg-4 col-md-4 col-sm-6">
                <div class="single-blog">
                    <div class="blog-thumb">
                        <img class="img-fluid" src="{% static 'img/blog/h-blog1.jpg' %}" alt="">
                    </div>
                    <div class="blog-details">
                        <div class="blog-meta">
                            <span>25 june, 2018 | By Mark Wiens</span>
                        </div>
                        <h5><a href="#">Addiction When Gambling <br>
                                Becomes A Problem</a></h5>
                        <p>Computers have become ubiquitous in almost every facet of our lives. At work, desk jockeys spend hours in
                            front of their desktops.</p>
                    </div>
                </div>
            </div>

            <div class="col-lg-4 col-md-4 col-sm-6">
                <div class="single-blog">
                    <div class="blog-thumb">
                        <img class="img-fluid" src="{% static 'img/blog/h-blog2.jpg' %}" alt="">
                    </div>
                    <div class="blog-details">
                        <div class="blog-meta">
                            <span>25 june, 2018 | By Mark Wiens</span>
                        </div>
                        <h5><a href="#">Addiction When Gambling <br>
                                Becomes A Problem</a></h5>
                        <p>Computers have become ubiquitous in almost every facet of our lives. At work, desk jockeys spend hours in
                            front of their desktops.</p>
                    </div>
                </div>
            </div>

            <div class="col-lg-4 col-md-4 col-sm-6">
                <div class="single-blog">
                    <div class="blog-thumb">
                        <img class="img-fluid" src="{% static 'img/blog/h-blog3.jpg' %}" alt="">
                    </div>
                    <div class="blog-details">
                        <div class="blog-meta">
                            <span>25 june, 2018 | By Mark Wiens</span>
                        </div>
                        <h5><a href="#">Addiction When Gambling <br>
                                Becomes A Problem</a></h5>
                        <p>Computers have become ubiquitous in almost every facet of our lives. At work, desk jockeys spend hours in
                            front of their desktops.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section> -->
<!--================ End Blog Area =================-->
 {% endblock %}